// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package barcode.proxies;

public class Barcode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject barcodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Barcode.Barcode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BarcodeFormat("BarcodeFormat"),
		ImageType("ImageType"),
		Encoding("Encoding"),
		ErrorCorrectionLevel("ErrorCorrectionLevel"),
		ErrorCorrection("ErrorCorrection"),
		Width("Width"),
		Height("Height"),
		BarcodeContent("BarcodeContent"),
		useTransparentBackground("useTransparentBackground");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Barcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Barcode.Barcode"));
	}

	protected Barcode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject barcodeMendixObject)
	{
		if (barcodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Barcode.Barcode", barcodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Barcode.Barcode");

		this.barcodeMendixObject = barcodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Barcode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static barcode.proxies.Barcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return barcode.proxies.Barcode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static barcode.proxies.Barcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new barcode.proxies.Barcode(context, mendixObject);
	}

	public static barcode.proxies.Barcode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return barcode.proxies.Barcode.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of BarcodeFormat
	 * @param barcodeformat
	 */
	public final barcode.proxies.BarcodeFormat getBarcodeFormat()
	{
		return getBarcodeFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of BarcodeFormat
	 */
	public final barcode.proxies.BarcodeFormat getBarcodeFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BarcodeFormat.toString());
		if (obj == null)
			return null;

		return barcode.proxies.BarcodeFormat.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BarcodeFormat
	 * @param barcodeformat
	 */
	public final void setBarcodeFormat(barcode.proxies.BarcodeFormat barcodeformat)
	{
		setBarcodeFormat(getContext(), barcodeformat);
	}

	/**
	 * Set value of BarcodeFormat
	 * @param context
	 * @param barcodeformat
	 */
	public final void setBarcodeFormat(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.BarcodeFormat barcodeformat)
	{
		if (barcodeformat != null)
			getMendixObject().setValue(context, MemberNames.BarcodeFormat.toString(), barcodeformat.toString());
		else
			getMendixObject().setValue(context, MemberNames.BarcodeFormat.toString(), null);
	}

	/**
	 * Set value of ImageType
	 * @param imagetype
	 */
	public final barcode.proxies.ImageType getImageType()
	{
		return getImageType(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageType
	 */
	public final barcode.proxies.ImageType getImageType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ImageType.toString());
		if (obj == null)
			return null;

		return barcode.proxies.ImageType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ImageType
	 * @param imagetype
	 */
	public final void setImageType(barcode.proxies.ImageType imagetype)
	{
		setImageType(getContext(), imagetype);
	}

	/**
	 * Set value of ImageType
	 * @param context
	 * @param imagetype
	 */
	public final void setImageType(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.ImageType imagetype)
	{
		if (imagetype != null)
			getMendixObject().setValue(context, MemberNames.ImageType.toString(), imagetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ImageType.toString(), null);
	}

	/**
	 * Set value of Encoding
	 * @param encoding
	 */
	public final barcode.proxies.Encoding getEncoding()
	{
		return getEncoding(getContext());
	}

	/**
	 * @param context
	 * @return value of Encoding
	 */
	public final barcode.proxies.Encoding getEncoding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Encoding.toString());
		if (obj == null)
			return null;

		return barcode.proxies.Encoding.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Encoding
	 * @param encoding
	 */
	public final void setEncoding(barcode.proxies.Encoding encoding)
	{
		setEncoding(getContext(), encoding);
	}

	/**
	 * Set value of Encoding
	 * @param context
	 * @param encoding
	 */
	public final void setEncoding(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.Encoding encoding)
	{
		if (encoding != null)
			getMendixObject().setValue(context, MemberNames.Encoding.toString(), encoding.toString());
		else
			getMendixObject().setValue(context, MemberNames.Encoding.toString(), null);
	}

	/**
	 * Set value of ErrorCorrectionLevel
	 * @param errorcorrectionlevel
	 */
	public final barcode.proxies.ErrorCorrection getErrorCorrectionLevel()
	{
		return getErrorCorrectionLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorCorrectionLevel
	 */
	public final barcode.proxies.ErrorCorrection getErrorCorrectionLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ErrorCorrectionLevel.toString());
		if (obj == null)
			return null;

		return barcode.proxies.ErrorCorrection.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ErrorCorrectionLevel
	 * @param errorcorrectionlevel
	 */
	public final void setErrorCorrectionLevel(barcode.proxies.ErrorCorrection errorcorrectionlevel)
	{
		setErrorCorrectionLevel(getContext(), errorcorrectionlevel);
	}

	/**
	 * Set value of ErrorCorrectionLevel
	 * @param context
	 * @param errorcorrectionlevel
	 */
	public final void setErrorCorrectionLevel(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.ErrorCorrection errorcorrectionlevel)
	{
		if (errorcorrectionlevel != null)
			getMendixObject().setValue(context, MemberNames.ErrorCorrectionLevel.toString(), errorcorrectionlevel.toString());
		else
			getMendixObject().setValue(context, MemberNames.ErrorCorrectionLevel.toString(), null);
	}

	/**
	 * @return value of ErrorCorrection
	 */
	public final java.lang.Integer getErrorCorrection()
	{
		return getErrorCorrection(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorCorrection
	 */
	public final java.lang.Integer getErrorCorrection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ErrorCorrection.toString());
	}

	/**
	 * Set value of ErrorCorrection
	 * @param errorcorrection
	 */
	public final void setErrorCorrection(java.lang.Integer errorcorrection)
	{
		setErrorCorrection(getContext(), errorcorrection);
	}

	/**
	 * Set value of ErrorCorrection
	 * @param context
	 * @param errorcorrection
	 */
	public final void setErrorCorrection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer errorcorrection)
	{
		getMendixObject().setValue(context, MemberNames.ErrorCorrection.toString(), errorcorrection);
	}

	/**
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth()
	{
		return getWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Width.toString());
	}

	/**
	 * Set value of Width
	 * @param width
	 */
	public final void setWidth(java.lang.Integer width)
	{
		setWidth(getContext(), width);
	}

	/**
	 * Set value of Width
	 * @param context
	 * @param width
	 */
	public final void setWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer width)
	{
		getMendixObject().setValue(context, MemberNames.Width.toString(), width);
	}

	/**
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight()
	{
		return getHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Height.toString());
	}

	/**
	 * Set value of Height
	 * @param height
	 */
	public final void setHeight(java.lang.Integer height)
	{
		setHeight(getContext(), height);
	}

	/**
	 * Set value of Height
	 * @param context
	 * @param height
	 */
	public final void setHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer height)
	{
		getMendixObject().setValue(context, MemberNames.Height.toString(), height);
	}

	/**
	 * @return value of BarcodeContent
	 */
	public final java.lang.String getBarcodeContent()
	{
		return getBarcodeContent(getContext());
	}

	/**
	 * @param context
	 * @return value of BarcodeContent
	 */
	public final java.lang.String getBarcodeContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BarcodeContent.toString());
	}

	/**
	 * Set value of BarcodeContent
	 * @param barcodecontent
	 */
	public final void setBarcodeContent(java.lang.String barcodecontent)
	{
		setBarcodeContent(getContext(), barcodecontent);
	}

	/**
	 * Set value of BarcodeContent
	 * @param context
	 * @param barcodecontent
	 */
	public final void setBarcodeContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String barcodecontent)
	{
		getMendixObject().setValue(context, MemberNames.BarcodeContent.toString(), barcodecontent);
	}

	/**
	 * @return value of useTransparentBackground
	 */
	public final java.lang.Boolean getuseTransparentBackground()
	{
		return getuseTransparentBackground(getContext());
	}

	/**
	 * @param context
	 * @return value of useTransparentBackground
	 */
	public final java.lang.Boolean getuseTransparentBackground(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.useTransparentBackground.toString());
	}

	/**
	 * Set value of useTransparentBackground
	 * @param usetransparentbackground
	 */
	public final void setuseTransparentBackground(java.lang.Boolean usetransparentbackground)
	{
		setuseTransparentBackground(getContext(), usetransparentbackground);
	}

	/**
	 * Set value of useTransparentBackground
	 * @param context
	 * @param usetransparentbackground
	 */
	public final void setuseTransparentBackground(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usetransparentbackground)
	{
		getMendixObject().setValue(context, MemberNames.useTransparentBackground.toString(), usetransparentbackground);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return barcodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final barcode.proxies.Barcode that = (barcode.proxies.Barcode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Barcode.Barcode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
